[package]
name = "libblockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
uuid = { version = "1.18.1", features = ["v4"] }
libcertcrypto = { path = "../libcertcrypto" }
openssl = "0.10"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
